services:
  - type: web
    name: dsc1-server
    runtime: python
    rootDir: server
    buildCommand: "cd .. && npm install && npm run build && cd server && pip install -e . && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
