# Generated by Django 5.2.16 on 2026-07-11 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_share_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="PdfImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("outlining", "Outlining"),
                            ("extracting", "Extracting"),
                            ("ready", "Ready"),
                            ("committed", "Committed"),
                            ("error", "Error"),
                        ],
                        default="outlining",
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=300)),
                ("pdf_b64", models.TextField(blank=True)),
                ("outline_batch_id", models.CharField(blank=True, max_length=100)),
                ("extract_batch_id", models.CharField(blank=True, max_length=100)),
                ("outline", models.JSONField(blank=True, default=dict)),
                ("rows", models.JSONField(blank=True, default=list)),
                ("review", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_import_jobs",
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
