# Generated by Django 5.2.16 on 2026-07-12 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_pdfimportjob"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PdfImportJob",
        ),
    ]
