[tox]
envlist = format, lint, type, tests
skipsdist = false

[testenv]
runner = uv-venv-lock-runner
extras = dev
setenv =
    DJANGO_SETTINGS_MODULE = config.settings
    SECRET_KEY = test-secret-not-for-production

[testenv:format]
commands = ruff format --check .

[testenv:lint]
commands = ruff check .

[testenv:type]
commands = mypy config api

[testenv:tests]
commands = python manage.py test -v 2
